/**
Project Euler Problem 1: Multiples of 3 and 5
Adapted from https://projecteuler.net/problem=1

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
**/
function problem_solver_1() 
{
	var counter = 3;
	var output = 0;

	while (counter < 1000) {
		if (counter % 3 === 0) 
		{
			output = output + counter;
		} else if (counter % 5 === 0) 
		{
			output = output + counter;
		}

		counter++;
	}
	console.log("problem one output = " + output);
	return output;
}

/**
Project Euler Problem 2: Even Fibonacci numbers
Adapted from https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
**/
function problem_solver_2() 
{
	var counter1 = 1;
	var counter2 = 2;
	var counter3 = 0;
	var output = 2;

	while (counter3 <  4000000)
		{
			counter3 = counter1 + counter2;
			if (counter3 % 2 === 0)
				{
					output += counter3;
				}
			counter1 = counter2;
			counter2 = counter3;
		}
	console.log("problem two output = " + output);
	return output;
}